name: Build and Push Docker Image

on:
  push:
    branches:
      - main   # Trigger workflow on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}   # Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}   # Docker Hub password (stored in GitHub Secrets)

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t alaricseq/linear-code:latest .

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push alaricseq/linear-code:latest
